.\" Manpage for pwds.
.TH man 1 "01 Nov 2021" "1.0" "pwds man page"
.SH NAME
pwds
.SH SYNOPSIS
pwds ls - lists all systems which have a password assigned.
.SH DESCRIPTION
A server password manager.
.SH OPTIONS
.IP -keyfile 
.IP -k 
Followed by your path to and name for key file.
.IP -dbfile
.IP -d 
Followed by your path to and name for database file.
.IP -username 
.IP -u 
Will add whoami to the begging of file name for db.
.IP -installpath
.IP -i 
Will install db to Scripts installed path.
.IP -home 
Will install db to your home directory.
.IP -dir 
Followed by your directory for the db file.
.IP -? 
.IP ? 
.IP help 
.IP --help 
.IP -help 
Gives help info.
.IP show 
Followed by ID# Will show more details for that item.
.IP add
.IP new 
Followed by item name then status if using todo.
.IP remove
.IP rm
.IP del
.IP delete 
Followed by ID# to remove an item.
.IP update-name 
.IP update-item 
Followed by ID# and new system name.
.IP update-pwd 
.IP update-password 
Followed by ID# and new password.
.IP enable 
.IP enabled 
Followed by ID# to mark as active.
.IP disable 
.IP disabled 
Followed by ID# to make as in-active.
.IP expires
Followed by ID# and Expires on Date.
.IP -desc 
.IP -latest
Changes the list order.
.IP -done
.IP -not-done 
Used in where clause to search for done or not-done items.
.IP -page # -limit # 
List pagination...IE -page 1 -limit 200.
.IP -p
.IP -pass 
.IP -password 
.IP -pwd 
Followed by password to use.
.IP -user 
Will show whoami the user that added todo item.
.IP -host 
Will show the hostname of computer that added todo item.
.IP -mdy
Will show date as month day year format.
.IP -dmy
Will show date as day month year format.
.IP -fancy
Will show date in a fancy format.
.IP -24hours
Will show time in military format.
.IP -time
Will show time with date.
.SH SEE ALSO

.SH BUGS
No known bugs.
.SH AUTHOR
Robert S.