.\" Manpage for todo.
.TH man 1 "01 Nov 2021" "1.0" "todo man page"
.SH NAME
todo
.SH SYNOPSIS
todo ls - lists all todo items.
.SH DESCRIPTION
What are things left todo on your server (password protected)...
.SH OPTIONS
.IP -keyfile 
.IP -k 
Followed by your path to and name for key file.
.IP -dbfile
.IP -d 
Followed by your path to and name for database file.
.IP -username 
.IP -u 
Will add whoami to the begging of file name for db.
.IP -installpath 
.IP -i 
Will install db to Scripts installed path.
.IP -home 
Will install db to your home directory.
.IP -dir 
Followed by your directory for the db file.
.IP -? 
.IP ? 
.IP help 
.IP --help 
.IP -help 
Gives help info.
.IP show followed by ID# 
Will show more details for that item.
.IP add 
.IP new 
Followed by item name then status.
.IP remove 
.IP rm 
.IP del 
.IP delete 
Followed by ID# to remove an item.
.IP update 
Followed by ID# and new description.
.IP complete 
.IP done 
Followed by ID# to mark as done.
.IP incomplete 
.IP not-done 
Followed by ID# to make as not-done.
.IP -desc 
.IP -latest 
Changes the list order.
.IP -done 
.IP -not-done 
Used in where clause to search for done or not-done items.
.IP -page # -limit # 
List pagination...IE -page 1 -limit 200.
.IP -p 
.IP -pass 
.IP -password 
.IP -pwd 
Followed by password to use.
.IP -user 
Will show whoami the user that added todo item.
.IP -host 
Will show the hostname of computer that added todo item.
.IP -mdy
Will show date as month day year format.
.IP -dmy
Will show date as day month year format.
.IP -fancy
Will show date in a fancy format.
.IP -24hours
Will show time in military format.
.IP -time
Will show time with date.
.SH SEE ALSO

.SH BUGS
No known bugs.
.SH AUTHOR
Robert S.
