[general]
start_url = ""
max_width = 200

[colors]
h1 = "red"
h2 = "#0099ff"
h3 = "#001a33"
list = "red"
text = "#c7ff96"
background = "#141a0f"
[colors.quote]
    foreground="#e4e4e4"
    background="grey"

[characters]
h1 = ". "
h2 = ".. "
h3 = "... "
list = "💡 "

[fonts]
[fonts.finger]
    family = "monospace"
    size = 12
[fonts.gemini.text]
    family = "serif"
    size = 13
[fonts.gemini.h1]
    family = "sans"
    size = 16
    style = "normal"
[fonts.gemini.h2]
    family = "monospace"
    size = 14
    style = "italic"
[fonts.gemini.h3]
    family = "monospace"
    size = 13
[fonts.gemini.list]
    family = "sans"
    size = 12
    style = "oblique"
[fonts.gemini.quote]
    family = "sans"
    size = 11
    style = "italic"
[fonts.gopher]
    family = "monospace"
    size = 12
